### ISSUE TITLE
solid-dnd.com is down!

### ISSUE THREAD

**Issue by membranobruno** [thisbeyond/solid-dnd#103]
Something has wrong with a website. The website is not opening.

TypeError: Ua is not a function. (In 'Ua()', 'Ua' is an instance of SVGSVGElement)

**Comment by martinpengellyphillips** [comment]
Thanks for reporting - looks like a recent dependency update broke the build. Will take a look to fix :)

**Comment by martinpengellyphillips** [comment]
Now fixed - thanks.
