### ISSUE TITLE
Delay when starting drag causes quirky behaviour

### ISSUE THREAD

**Issue by Jakst** [thisbeyond/solid-dnd#11]
I haven't tried the library out yet, but noticed this issue on [https://solid-dnd.com](https://solid-dnd.com), so I figured I might report them.

There's a delay before an item starts tracking under the cursor, which leads to a big jump when clicking and dragging quickly on an item. You should easily be able to reproduce this on the webpage. 

It becomes more quirky when dragging quickly on the sortable list in the examples, because then the item underneath the cursor changes to the ones you have passed on the way, and so the first item that starts tracking under the cursor is not the same one that you started dragging on. Try to for example drag "Sortable 3" quickly upwards over the other sortables. It will never render with Sortable 3 under the cursor. This makes dragging feel a bit clunky.

**Comment by martinpengellyphillips** [comment]
Thanks for the report! 

I can reproduce the behaviour. 

The delay is currently hardcoded in the pointer sensor at 250ms, which felt a sensible value to avoid confusion with typical clicks.

We can make that configurable, but I think we'd also need to introduce a move distance check to address this properly. E.g. Wait 250ms OR for move of 10+pixels to start drag.

**Comment by Jakst** [comment]
> I can't reproduce the wrong item being dragged though. Logically that shouldn't be possible because the draggable id is captured at time of click.

I think I might have confused myself when writing that. Sorry! I did not mean that the wrong item gets tracked, but rather that the visual effect of the delay gives you the feeling that you are dragging on the last item you passed, instead of the the first one. So in my example it feels like you are dragging Draggable 1 instead of Draggable 3, even though Draggable 3 is still the one under the cursor in the end of course. This is probably because the placeholder for Draggable 3 is moved to Draggable 1's position before the timeout has run out.

Setting an additional check for drag distance sounds like a promising fix to this issue to me!
