### ISSUE TITLE
Sorting across multiple lists - kanban table

### ISSUE THREAD

**Issue by martinpengellyphillips** [thisbeyond/solid-dnd#15]
From #14 there is a request to be able to sort across multiple lists (like a kanban table) easily. Whilst this is possible today, it likely requires lower level use of the library. 

Work up an example and then see if any updates to the library are needed to make this more plug and play, especially when using the existing sortable layer.

**Comment by hangtwenty** [comment]
> Whilst this is possible today, it likely requires lower level use of the library.

I would love to see an example of multiple sortable lists / moving items between them. I was able to combine some of the other examples on the project page (like sortable and drag handles) but I haven't figured out how to combine sortable and multiple drop-zones.

**Comment by martinpengellyphillips** [comment]
Yeah, I  will take a look at this in the coming weeks - I actually haven't tried it yet so will be interesting to see what works/needs improvement.

**Comment by martinpengellyphillips** [comment]
Making progress here (and some good improvements to the library). Once complete, Solid DnD should naturally handle the case where an active draggable is re-parented/re-created mid-drag (such as when moving between multiple containers). That should make a kanban board example easier to create. Note that this will just be one approach - a more interesting and perhaps challenging approach longer term would be to compute a transform across multiple containers _without_ reparenting the draggable.

**Comment by martinpengellyphillips** [comment]
Will try to finish and release this over the weekend @hangtwenty

![solid-dnd-multiple-lists-example](https://user-images.githubusercontent.com/214338/162537496-eaecf273-487f-4373-af7d-677ff564f393.gif)

**Comment by timothyallan** [comment]
This looks great. Would this also work with a list of items which wrap in a flex row with `flex-wrap` turned on?
That way the browser width determines the amount of columns.

**Comment by jcuenod** [comment]
I'm dreaming of a [dnd layout UI](https://jcuenod.github.io/parabible-experiments/draggable/) in which the user can grab a tab and drag to reorder or create split panes. I'm planning on using the multiple lists for tabbars but I haven't figured out the droppables for to create splits.

**Comment by martinpengellyphillips** [comment]
> Would this also work with a list of items which wrap in a flex row with flex-wrap turned on? That way the browser width determines the amount of columns.

@timothyallan Maybe. We could give it a go. Might require some additional work. Certainly _should_ be possible.

**Comment by martinpengellyphillips** [comment]
FYI My current goal is to get this released this weekend (hit a bug earlier on that delayed things a bit).

**Comment by martinpengellyphillips** [comment]
This is now released in [0.5.0](https://github.com/thisbeyond/solid-dnd/releases/tag/0.5.0) and a multiple list example added to https://solid-dnd.com/ 🎉 

Note: this release contains breaking changes - see changelog for details.
