### ISSUE TITLE
Consider using components instead of directives

### ISSUE THREAD

**Issue by areknawo** [thisbeyond/solid-dnd#18]
Let me first say a big "Thank you!" for the work you've done on this project. It's great to see the Solid community and ecosystem grow!

I understand you're using directives as a way to inject dnd functionality to the elements while leaving the user full control over them. The idea is good, however, I'd argue it's not the way to go.

I consider directives the most "whacky" feature of Solid. As to why:
- they're unique among JSX-based frameworks and thus harder to understand for newcomers;
- they're tough to strongly type in TypeScript;
- they don't work with [Solid custom components](https://github.com/solidjs/solid/discussions/722)

That's my personal view, and I've stumbled upon the above issues while using this library.
I'd recommend exploring ways to provide an alternative or complete replacement for directives. Potential solutions include wrapper components, `<Dynamic/>` component as well as e.g. `ref`-passable function.

I'm interested to hear your thoughts on this.
I'm already working on strong TS typings for this library and could explore implementing such an alternative.

**Comment by areknawo** [comment]
Closing as I've found from the code & changelog that it's already possible.

**Comment by martinpengellyphillips** [comment]
Hey, thanks for the kind words and taking the time to share your thinking.

I'm usually not a fan of 'magic', but I actually find Solid directives quite ergonomic - a nice way to reduce potential boilerplate. So long as there is still a way to get at the underlying wiring - which you've found :)

I would love to hear the specifics of where you stumbled initially - maybe I should add another example to the website that avoids directives and shows the alternative approach? 

> I'm already working on strong TS typings for this library

That's great to hear - I'm still inexperienced in TS so very happy to accept contributions here.

**Comment by areknawo** [comment]
The issue was me trying to use a directive with a custom `<Card/>` component. I've only recently found out it's not possible, which IMHO, limits the potential of the directives greatly.

The alternative approach provided by solid-dnd works well in this case. A custom component just needs to properly pass the props and it's all good. I think bringing over the example from Changelog would be enough to give a hit to users that such an alternative exists.

On top of that, to work well with strongly-typed TS, directives need to be specified in a declaration file, which isn't a great experience considering their dynamic nature (i.e. you can just randomly name a function and use it as a directive).

As for typings - I'm mostly done there, though at this point I've also done other changes to the code. Things like different *tsconfig.json* file, Vite-powered build pipeline, and slightly different code style with e.g. parameters "unwrapped" from objects wherever it's logical (helps with typing + personal preference).

Let me know if you would accept such changes in the main repo. Otherwise, I'll try to reapply the typings to the base code without the changes - will just need more time. You can see the current progress in [my fork](https://github.com/areknawo/solid-dnd). Solving the last few bugs right now.

**Comment by martinpengellyphillips** [comment]
Makes sense - I'll look at adding that example to the doc site. Thanks for the context. 

> Let me know if you would accept such changes in the main repo. Otherwise, I'll try to reapply the typings to the base code without the changes - will just need more time.

I'm open to other changes so long as there is a sense of consistency (and stylistically it still adheres to prettier autoformat). It might take me a bit longer to review and merge though compared to just typings in isolation. But how about you throw up a merge request when you're ready and we can give it a go! I'm sure there will be a bit of back and forth anyway as I learn about the typings :)
