### ISSUE TITLE
Request for another example: like the Board example, but using createResource and/or real documents

### ISSUE THREAD

**Issue by hangtwenty** [thisbeyond/solid-dnd#35]
The examples are really helpful, but without another example that uses some multi-field records as the data, it's hard to generalize from the current examples. Part of the reason is that the examples treat all of the data as basically IDs; rather than displaying any additional content, they are just displaying IDs. The other missing piece is that these examples are using simple data that is synchronous, whereas real use cases more likely use `createResource` and/or data from async functions such as fetches. As I adapt the current examples to use real data from `createResource`, it feels like things get complicated quickly.

**Comment by martinpengellyphillips** [comment]
I've made the website repo (https://github.com/thisbeyond/solid-dnd-site) public now so you can raise PRs against it that we can collaborate on for more examples.

Regarding async - typically I would use an explicit `order` field for ease of syncs across devices which would make a good example. That said, I'm not sure how things get more complicated with async - would be good to see an example from you of the challenges encountered.

**Comment by hangtwenty** [comment]
@martinpengellyphillips Thanks for publishing the docsite, that'll make it cleaner to make a variation on an example. I'll try to make a clear example of what I'm talking about.

**Comment by hangtwenty** [comment]
Closing for now, since the docsite is its own repo
