### ISSUE TITLE
Edge case can happen where dragging breaks until page reload (— sometimes state.active.draggable becomes null and stays null?)

### ISSUE THREAD

**Issue by hangtwenty** [thisbeyond/solid-dnd#36]
(Unfortunately I don't have a reproduction for this yet, because my attempt at reproduction code isn't showing the problem; it's only showing in private code that I'm not able to share. I'll try to sort that out.)

It seems like a subtle state bug can happen in `drag-drop-context`. Given an application similar to the Board example  — i.e. two types of draggables, containers and items — if I drag an item, then drag a container, then drag an item again,[^1] sometimes solid-dnd breaks and dragging stops happening. (**EDIT: Dragging stops working for items; containers can still be dragged.**) It doesn't start working again until page refresh. What I've figured out so far is that somehow, `state.active.draggable` stops being set.

I'll keep trying to reproduce it cleanly. In the meantime, I wanted to share what I'm seeing, in case you have a sense of what might be going on.

(One thing I might try is to have `state.active.draggable` be its own signal in `drag-drop-context`; have a hunch that something weird is going on with the nested store get/sets and/or the usages of `untrack`.)

[^1]: ~It seems to involve _most_ items, but usually not all?~ **EDIT:** It affects the Items under any Container that's been dragged.

**Comment by martinpengellyphillips** [comment]
Interesting. It not starting again makes me think the sensor is not activating / is stale. Are there any other event listeners in your setup? Is it possible something is intercepting the events?

Also, are you reparenting items across containers?

**Comment by hangtwenty** [comment]
@martinpengellyphillips that's a good lead, I'll try looking into that. (I put lots of logging in drag-overlay to try to pinpoint the issue, but I haven't dug into the DragSensor yet; will do!)

**Comment by hangtwenty** [comment]
> Also, are you reparenting items across containers?

The bug can happen with or without any "drops" successfully completing. At the moment, I broke the code for dropping, but the bug still appears - it happens at the time of dragging. So to be clear, it can happen from just drag of an item, then drag of a container, then drag of an item (with each "drag" being quick/ not repositioning anything).

**Comment by hangtwenty** [comment]
I think I've narrowed down the behavior a little bit: it seems like it affects the items that are children of a parent, after dragging the parent. So, dragging a list does not break all items, it just breaks the items that are children of a list-that's-been-dragged.

Also noticing that it does successfully switch to showing DragOverlay for the dragged item, so _some_ part of the activation is working. But it doesn't drag the element around.

**Comment by hangtwenty** [comment]
`<DragDropDebugger />` is really handy! It just revealed a little more of what's going on. Before it breaks, the containers are outlined in blue and the items are outlined in red. After it breaks, the items (that have broken) are no longer outlined in red.

**Comment by hangtwenty** [comment]
I _think_ I found the root cause.

I was using two DragOverlays, one for the Container and one for the Item. In the Container Overlay, I had it using the same Container component as I'm using in the main layout. That component has a `<SortableProvider>` in it. I replaced the contents of the Container Overlay with some dummy text, and the issue stops happening — dragging items still works after dragging a container. So it's something about the nested/extra SortableProvider; maybe that's "clobbering" something in solid-dnd's state. It makes sense now that I think about it: the SortableProvider inside the Container Overlay has a list of IDs that match the SortableProvider inside the corresponding Container. When dragging a Container, the Container Overlay is instantiated and it has a SortableProvider with the same IDs as the real Container's SortableProvider. So they get overwritten. And/or, maybe they get "cleaned up" when the Container Overlay is destroyed (i.e. releasing drag). Does that make sense? I can try to explain better if it doesn't.

I think it will be fixed if I just make sure my Container Overlay does not have a SortableProvider inside of it. I'll confirm shortly.

**Comment by hangtwenty** [comment]
Confirmed, that seems to be the cause!

Probably worthwhile to document it or even detect it to print a warning. (i.e. maybe inside SortableProvider, use DragOverlay context just to check if it's inside a DragOverlay and log a warning if so..?)

**Comment by martinpengellyphillips** [comment]
Nice debugging!

I think #17 would help a lot here in future. Essentially, the drag overlay should be a 'display only' component and not interactive/draggable/sortable ever.

As you saw, when you instantiate the container duplicate in the overlay, you effectively re-register all the draggables/droppables with the same IDs, but now attached to the components/items in that container. And when it is cleaned up all of the corresponding state will be removed. 

So whilst `SortableProvider` is a factor, this would happen anyway without it if you recreated a draggable with the same id inside the drag overlay.
