### ISSUE TITLE
Intermittent error from removeDraggable

### ISSUE THREAD

**Issue by hangtwenty** [thisbeyond/solid-dnd#38]
This is probably self-inflicted due to a usage error on my part, but I'm seeing this sometimes (and it breaks behavior):

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_pendingCleanup')
    at updatePath (dev.js:168:12)
    at updatePath (dev.js:165:7)
    at updatePath (dev.js:165:7)
    at dev.js:193:17
    at batch (dev.js:415:14)
    at setStore (dev.js:193:5)
    at removeDraggable (drag-drop-context.jsx:91:9)
    at Array.<anonymous> (create-draggable.js?t=1652401249008:19:21)
    at cleanNode (dev.js:936:62)
    at cleanNode (dev.js:932:45)
```

Is it possible that no cleanup is required in that case? (Could it soft-fail?)

**Comment by martinpengellyphillips** [comment]
Looks like you are attempting to remove a draggable that doesn't exist (though the error could be better here).

Are you calling `removeDraggable` manually perhaps?

I guess we should check the draggable exists and issue a warning when attempting to remove one that doesn't.

**Comment by hangtwenty** [comment]
I'm not manually calling `removeDraggable`, but maybe it's being called redundantly for some reason. If it's possible to soft-fail with a warning, it seems like it would solve it in my case.

**Comment by martinpengellyphillips** [comment]
I'll be cutting a new release soon so will try to add that in.

**Comment by martinpengellyphillips** [comment]
Better late than never? 😂 

Warnings added in [0.7.1](https://github.com/thisbeyond/solid-dnd/releases/tag/0.7.1)
