### ISSUE TITLE
Update for Solid 1.4.x

### ISSUE THREAD

**Issue by martinpengellyphillips** [thisbeyond/solid-dnd#39]
Typings and other notable changes in 1.4, so update and make this the min compat version for solid-dnd now.

**Comment by martinpengellyphillips** [comment]
@hnagrath09 that would be great and I'm very open to help. 

To be transparent though - I'm working on a significant refactor right now so some of the work on typings might be redundant. If you don't mind that, then please go for it!

**Comment by hnagrath09** [comment]
What kind of approach are you using to fix the definitions? I usually use the following pattern:

```
type SomeComponentProps = {
  children: JSX.Element
  // other props
}

export default function SomeComponent(props: SomeComponentProps) {
  // component implementation
}
```

**Comment by martinpengellyphillips** [comment]
I'd probably just be replacing `Component` with [`ParentComponent`](https://www.solidjs.com/guides/typescript) etc where appropriate. 

E.g. 

```
const DragDropProvider: ParentComponent<DragDropContextProps> = (passedProps) => {
   ...
}
```

Also, exports are currently at the bottom of each file explicitly rather than inline.

**Comment by hnagrath09** [comment]
Got it!! Will raise a PR soon.
