### ISSUE TITLE
Property 'children' does not exist on type

### ISSUE THREAD

**Issue by Ehesp** [thisbeyond/solid-dnd#40]
Hey, 

"solid-js": "^1.3.13",
"@thisbeyond/solid-dnd": "^0.6.1",

When rendering both a `DragDropProvider` and `SortableProvider`, I'm getting the error:

```
property 'children' does not exist on type 'IntrinsicAttributes & DragDropContextProps'
```

Copied the code straight from the docs.

**Comment by martinpengellyphillips** [comment]
I think this is due to changes made in SolidJS recently. I've got an open issue (#39) to update to latest and greatest, which should address this.

**Comment by martinpengellyphillips** [comment]
By the way, the code should work - it's just a typing issue.

**Comment by martinpengellyphillips** [comment]
Closing as duplicate of #39
