### ISSUE TITLE
`useSortableContext` sometimes returns `null`

### ISSUE THREAD

**Issue by moseschmiedel** [thisbeyond/solid-dnd#43]
In `create-sortable.ts` you use the `useSortableContext` hook [here](https://github.com/thisbeyond/solid-dnd/blob/20edbb68f3ba195df7e89c952e994ca7d9351557/src/create-sortable.ts#L25) and destructure the return value as an array. You typed `useSortableContext` so that it could return `null`. In theory this should never happen, if `createSortable` gets called inside a Component, that is a child of a `SortableProvider`, but in praxis i get this error
```
index.js:3452 Uncaught TypeError: useSortableContext is not a function or its return value is not iterable
    at createSortable (index.js:3452:29)
```
despite using the `createSortable` function inside of a Component that is a child of a `SortableProvider`.
I suspect that there is some weird circumstance, where the `SortableContext` is not yet established, but `createSortable` gets already called. If you wish i could share the code with you in which i'm using the `SortableProvider` and `createSortable`. As this is in an open source project, it's no problem if i show it here...

**Comment by martinpengellyphillips** [comment]
Interesting! As you say, it should _not_ happen, but never say never :)

If you can share an example that would help debug this for sure.

**Comment by moseschmiedel** [comment]
Thank you for your quick response.

Here are the lines where the `SortableProvider` gets initialized and `createSortable` gets called.
- [`SortableProvider`](https://github.com/moseschmiedel/solid-coocook-components/blob/7f13a25ba4f7fcffbcfa37b44a2cdb8bc95e6819/src/components/IngredientsEditor.tsx#L203)
- [`createSortable`](https://github.com/moseschmiedel/solid-coocook-components/blob/7f13a25ba4f7fcffbcfa37b44a2cdb8bc95e6819/src/components/Ingredient.tsx#L24)

If you have further questions, feel free to ask me. But I will not be able to answer them until tomorrow. As it's getting late, where I am.

**Comment by martinpengellyphillips** [comment]
Thanks - yep I can see the issue. You are using `<Ingredient>` (which calls `createSortable`) outside of the `SortableProvider` in your `<DragOverlay>`. See [here](https://github.com/moseschmiedel/solid-coocook-components/blob/7f13a25ba4f7fcffbcfa37b44a2cdb8bc95e6819/src/components/IngredientsEditor.tsx#L189) . 

I need to write docs to make this clearer in future, but your overlay component should not itself be a draggable/droppable/sortable item. It should be a 'presentational' component only (no logic).

**Comment by moseschmiedel** [comment]
Oh, yeah I forgot about that call of `<Ingredient>`. Thank you for your help.

I close this issue, because I see it as resolved.
