### ISSUE TITLE
Has this library touch support?

### ISSUE THREAD

**Issue by ivanjeremic** [thisbeyond/solid-dnd#45]
Hello, from the Website I can't find any information on touch support, so does this library have touch support?

**Comment by martinpengellyphillips** [comment]
Yes, the default sensor is based on pointer events and so supports touch. 

If you visit the website on a touch device you should be able to use touch on any example. 

You can also build your own sensors if you need something other than the default. 

Note, there is no support for multi touch.

**Comment by ivanjeremic** [comment]
> Yes, the default sensor is based on pointer events and so supports touch.
> 
> If you visit the website on a touch device you should be able to use touch on any example.
> 
> You can also build your own sensors if you need something other than the default.
> 
> Note, there is no support for multi touch.

Ok nice that means it automatically knows if the user is on desktop with a mouse or if he uses a tablet/smartphone, I was not used to this because in other frameworks I need to initialize every sensor myself based on conditions, an I seeing this right? Regarding multi touch I honestly need to lookup what that even is never heard of it.

**Comment by martinpengellyphillips** [comment]
Correct. Just using the default  `<DragDropSensors />` will give you mouse and touch support automatically. No need for further setup.

**Comment by ivanjeremic** [comment]
Thanks, by the way to not open another issue I get a bunch of typescript errors like
 ```
Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes & DragOverlayProps'.ts(2559)
```
when I use the sortable list example, the errors are on every component like `DragDropProvider` `SortableProvider` `DragOverlay` any ideas?

**Comment by martinpengellyphillips** [comment]
Yep it's due to #39

There's a pr up for it, I'm just recovering from illness so a bit delayed in releasing.

**Comment by ivanjeremic** [comment]
> Yep it's due to #39
> 
> There's a pr up for it, I'm just recovering from illness so a bit delayed in releasing.

Thanks, wish you all the best.
