### ISSUE TITLE
Solid-dnd help for sortable needed (CodeSanbox) Example.

### ISSUE THREAD

**Issue by ivanjeremic** [thisbeyond/solid-dnd#46]
Besides being new to Solid I try also to implement dnd for my use-case and I have created an CodeSandBox which I try now for the last 2 hours to get working without success, maybe I'm just doing something wrong in the solid side coming from react.js or maybe also some issues with the way how I try to read the dnd data, I really don't know what it could be.

[https://codesandbox.io/s/solid-dnd-problem-gjlp8f](https://codesandbox.io/s/solid-dnd-problem-gjlp8f)
 (open codesanbox preview in new window, for some reason only in the real tab console works.)

Thanks

**Comment by martinpengellyphillips** [comment]
Similar to #41 - your `createSortable` needs to be passed an identifier not, the whole item. Same goes for `ids` props - it should be a list of the unique identifiers. 

Take a look at this fork of your example to see what I mean: https://codesandbox.io/s/solid-dnd-problem-forked-76jz5w

**Comment by ivanjeremic** [comment]
Thank you very much, the missing part what I don't understand now how would I make the drop work successful because `onDrop` the whole grid  turns weird instead of accepting the new order?

**Comment by martinpengellyphillips** [comment]
You need to ensure you are updating the `ids` array to reflect the new order. E.g. https://codesandbox.io/s/solid-dnd-desk-forked-ojr74x

**Comment by ivanjeremic** [comment]
> You need to ensure you are updating the `ids` array to reflect the new order. E.g. https://codesandbox.io/s/solid-dnd-desk-forked-ojr74x

Thanks, I changed that part while experimenting and forgot to change it back.

**Comment by ivanjeremic** [comment]
> You need to ensure you are updating the `ids` array to reflect the new order. E.g. https://codesandbox.io/s/solid-dnd-desk-forked-ojr74x

On line 63 is the issue I mean I have commented the issue in this new SandBox [https://codesandbox.io/s/solid-dnd-desk-droppable-id-4b7n4l?file=/src/main.tsx](https://codesandbox.io/s/solid-dnd-desk-droppable-id-4b7n4l?file=/src/main.tsx)
