### ISSUE TITLE
droppable data inside `onDragOver` (dragenter)?

### ISSUE THREAD

**Issue by ivanjeremic** [thisbeyond/solid-dnd#47]
Native HTML5 DND has `dragenter`, which allows us to execute logic when a dragged element enters. Getting `droppable` data only inside `onDragEnd` is not enough I think because there are legit use-cases where the data of the `droppable` is needed when entered with a dragged element. 

One way could be give us `droppable` data inside `onDragOver`, I have even tested this if I'm able to read `droppable` data inside `onDragOver` and interestingly I can log the ID of the `droppable` when "pretending " to drag (press and hold) and move around but the element does not actually go with me for some reason.

What I have also tried is to add the `onDragEnter` event to the element directly but it seems not to be able to work in combination with this library.

If there is any way to get droppable data when entering it with and dragged element, even with workarounds I would appreciate it. 

Thanks

**Comment by martinpengellyphillips** [comment]
I'm not following what the issue is. You can use `onDragOver` which is passed the currently active `droppable` (and will be reactively called whenever it changes). What's not working for you with that? 

Note: This library doesn't use native dnd events at all as they are too limiting for most use cases.

**Comment by ivanjeremic** [comment]
> I'm not following what the issue is. You can use `onDragOver` which is passed the currently active `droppable` (and will be reactively called whenever it changes). What's not working for you with that?
> 
> Note: This library doesn't use native dnd events at all as they are too limiting for most use cases.

> You need to ensure you are updating the `ids` array to reflect the new order. E.g. https://codesandbox.io/s/solid-dnd-desk-forked-ojr74x

On line 63 is the issue I have commented the issue in this new SandBox [https://codesandbox.io/s/solid-dnd-desk-droppable-id-4b7n4l?file=/src/main.tsx](https://codesandbox.io/s/solid-dnd-desk-droppable-id-4b7n4l?file=/src/main.tsx) Thanks

**Comment by martinpengellyphillips** [comment]
`droppable` will be `null` when not over a droppable. 

This is why you get the error `Uncaught TypeError: droppable is null` when you try to access `droppable.id` without checking `droppable` is defined.

**Comment by ivanjeremic** [comment]
> `droppable` will be `null` when not over a droppable.
> 
> This is why you get the error `Uncaught TypeError: droppable is null` when you try to access `droppable.id` without checking `droppable` is defined.

So sorry for asking these basic questions I'm a bit overwhelmed learning solid and same time rewriting my project in it, you are right it works now when checking. Thanks I will close this now.

**Comment by martinpengellyphillips** [comment]
No worries - there's always something to learn :)
