### ISSUE TITLE
Sortable movement constraints.

### ISSUE THREAD

**Issue by ElitoGame** [thisbeyond/solid-dnd#49]
Hello there! I've stumbled across this toolkit today and I really liked what I saw, however I was missing a few user experience options, that I saw in libraries like JqueryUI. It would be awesome if those could be added as part of the Rewrite I read about in another Issue, or later down the line in another update. If wanted I can help out in developing these requested features, however, due to the planned Rewrite, opening an Issue first seemed like a smarter idea to me. (I am mainly referring to Sortable lists in this issue, since that is the feature I need for my project, however some of these ideas, might very well be useful for other draggable objects)
### X/Y axis constraints:
When designing a App, like a TODO app or similar, you most often only want the users to re-arrange items in one direction, so X || Y, depending on if it's a vertical or horizontal sortable. With the current system, users are able to move the Component anywhere in the whole page, along any axis, which might be a bit confusing for the user experience.
Inspiration: [JqueryUI Axis](https://api.jqueryui.com/sortable/#option-axis)
### Parent constraints:
Currently a draggable container can be moved anywhere in the page without constraints. However, bigger sites with multiple Lists or overlapping UIs, might just want to limit the movement of a item to it's parent container.
Inspiration: [JqueryUI Containment](https://api.jqueryui.com/sortable/#option-containment)

Thanks for the time, the toolkit looks pretty good 👍

**Comment by martinpengellyphillips** [comment]
This is now possible in [0.7.0](https://github.com/thisbeyond/solid-dnd/releases/tag/0.7.0) by applying a custom transformer. See example in release notes or on https://solid-dnd.com
