### ISSUE TITLE
[Typescript] Property 'children' does not exist on type 'IntrinsicAttributes & DragDropContextProps'.

### ISSUE THREAD

**Issue by Supertigerr** [thisbeyond/solid-dnd#52]
When I use the Sortable List (Vertical) example in a typescript SolidJs project, I get these errors:
```
Property 'children' does not exist on type 'IntrinsicAttributes & DragDropContextProps'.
```

Stackblitz link: https://stackblitz.com/edit/vitejs-vite-e5xr4s?file=src/list.tsx

Other than the typescript errors, The code seems to be working. But the errors are annoying.

**Comment by Supertigerr** [comment]
From what i can see, it seems like you didnt run `npm run build` or something. 
when i build from source, i see:
```ts
// "solid-dnd\dist\types\drag-drop-context.d.ts"
declare const DragDropProvider: ParentComponent<DragDropContextProps>;
```

And in the published NPM version, I can see:
```ts
declare const DragDropProvider: Component<DragDropContextProps>;
```

**Comment by martinpengellyphillips** [comment]
hey - yeah, latest main branch is not released yet. I'm getting back to it now though.

**Comment by martinpengellyphillips** [comment]
[0.7.0](https://github.com/thisbeyond/solid-dnd/releases/tag/0.7.0) is now released with updated typings and support for SolidJS 1.5+
