### ISSUE TITLE
Example suggest add touch-action:none tips

### ISSUE THREAD

**Issue by ymzuiku** [thisbeyond/solid-dnd#59]
Solid-dnd is great dnd package.
I use https://solid-dnd.com/ example,  but it can't drag in touch/mobile. Because i didn't know need add touch-action:none to Draggable Element. I use many hour until view your website class detail, i know i miss the touch-action:none.

Example suggest add touch-action:none tips, to help some people like me, like this:

```jsx
const Droppable = (props) => {
  const droppable = createDroppable(1);
  return (
    <div
      use:droppable
      // if your need use touch event, you need add touch-action:none
      style={{"touch-action":"none"}}
    >
      Droppable.
      {props.children}
    </div>
  );
};

```

**Comment by martinpengellyphillips** [comment]
Thanks for the kind words.

I think I need to invest in better docs now to cover things like these tips. Related issue https://github.com/thisbeyond/solid-dnd/issues/17

**Comment by peterboyer** [comment]
@ymzuiku Thank you very much for this suggestion/solution; I also got stuck on this for touch/mobile dragging!

**Comment by rmortes** [comment]
Thanks for the tip, you're a life saver!

**Comment by martinpengellyphillips** [comment]
Added an explicit mobile example to the website to make this more apparent.
https://solid-dnd.com/?example=Mobile%2520support
