### ISSUE TITLE
Uncaught TypeError: useDragDropContext is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by mykhaliuk** [thisbeyond/solid-dnd#63]
In newly created Solid.js application from template, installing the `solid-dnd` dependencies and copy-paste an example I have the next error within the white page:
```
create-pointer-sensor.js?v=88ebfb3e:4 Uncaught TypeError: useDragDropContext is not a function
 or its return value is not iterable
    at createPointerSensor (create-pointer-sensor.js?v=88ebfb3e:4:108)
    at DragDropSensors (drag-drop-sensors.jsx:3:5)
    at dev.js:515:12
    at untrack (dev.js:421:12)
    at Object.fn (dev.js:511:37)
    at runComputation (dev.js:691:22)
    at updateComputation (dev.js:676:3)
    at devComponent (dev.js:522:3)
    at createComponent (dev.js:1222:10)
    at get children [as children] (App.tsx:156:2)
```

<details>
  <summary>App.tsx</summary>

```tsx
import { Component, For } from "solid-js";

import {
	DragDropProvider,
	DragDropSensors,
	DragOverlay,
	createDraggable,
	DragEventHandler,
} from "@thisbeyond/solid-dnd";

const Draggable = (props) => {
const draggable = createDraggable(props.id);
  return (
    <div
      use:draggable
      class="draggable absolute"
      classList={{ "opacity-25": draggable.isActiveDraggable }}
      style={{ top: 0, left: (props.id === 1 ? 0 : 125) + "px" }}
    >
      Draggable {props.id}
    </div>
  );
};

export const DragMoveExample = () => {
  let transform = { x: 0, y: 0 };

  const onDragMove: DragEventHandler = ({ overlay }) => {
    if (overlay) {
      transform = { ...overlay.transform };
    }
  };

  const onDragEnd: DragEventHandler = ({ draggable }) => {
    const node = draggable.node;
    node.style.setProperty("top", node.offsetTop + transform.y + "px");
    node.style.setProperty("left", node.offsetLeft + transform.x + "px");
  };

  return (
    <DragDropProvider onDragMove={onDragMove} onDragEnd={onDragEnd}>
      <DragDropSensors />
      <div class="min-h-15 w-full h-full relative">
        <Draggable id={1} />
        <Draggable id={2} />
      </div>
      <DragOverlay>
        {(draggable) => <div class="draggable">Draggable {draggable.id}</div>}
      </DragOverlay>
    </DragDropProvider>
  );
};

const App: Component = () => {
  return (
      <>
        <DragMoveExample />
        <p class="text-4xl text-green-700 text-center py-20">Hello tailwind!</p>
    </>
  );
};

export default App;
```
</details>

<details>
<summary>package.json</summary>

```json
{
  "name": "dnd",
  "version": "0.0.1",
  "description": "",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "serve": "vite preview"
  },
  "license": "MIT",
  "devDependencies": {
    "autoprefixer": "^10.4.8",
    "postcss": "^8.4.16",
    "tailwindcss": "^3.1.8",
    "typescript": "^4.8.2",
    "vite": "^3.1.4",
    "vite-plugin-solid": "^2.3.9"
  },
  "dependencies": {
    "@thisbeyond/solid-dnd": "^0.7.1",
    "solid-js": "^1.5.7"
  }
}

```
</details>

Thank you in advance for any thought on this point. 

Might be i'm doing something wrong, cause I just started to dig into solid ^^

**Comment by martinpengellyphillips** [comment]
Hmm. That's definitely unexpected. I'll try and take a look at the weekend.

**Comment by martinpengellyphillips** [comment]
Oh wait, what does your vite config look like?

**Comment by MangKong-coder** [comment]
Hello! Is this issue resolved? If yes, would like to know what happened? If no, I also need some help regarding the same issue.

**Comment by martinpengellyphillips** [comment]
I'll need an example repo of this happening in order to help more. Can you share a link to where this is occurring for you?

**Comment by membranobruno** [comment]
Hi! The same problem.
```
create-draggable.js?v=49d3789b:6 Uncaught (in promise) TypeError: useDragDropContext is not a function or its return value is not iterable
    at createDraggable (create-draggable.js?v=49d3789b:6:77)
    at _Hot$$Folder (Folder.jsx:8:20)
    at @solid-refresh:10:42
    at untrack (dev.js:421:12)
    at Object.fn (@solid-refresh:10:28)
    at runComputation (dev.js:691:22)
    at updateComputation (dev.js:676:3)
    at createMemo (dev.js:238:10)
    at hmrCompWrapper (@solid-refresh:7:20)
    at dev.js:515:12
```

**Comment by martinpengellyphillips** [comment]
Check your `vite.config.ts` contains the following:

```js
optimizeDeps: {
  extensions: ["jsx"],
},
```

For example:

```js
import { defineConfig } from 'vite';
import solidPlugin from 'vite-plugin-solid';

export default defineConfig({
  plugins: [solidPlugin()],
  server: {
    port: 3000,
  },
  build: {
    target: 'esnext',
  },
  optimizeDeps: {
    extensions: ["jsx"],
  },
});

```

**Comment by membranobruno** [comment]
My config:
```
import { defineConfig } from "vite"
import solidPlugin from "vite-plugin-solid"
const path = require("path")

export default defineConfig({
  plugins: [solidPlugin()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  server: {
    port: 3000,
  },
  build: {
    target: "esnext",
  },
  optimizeDeps: {
    extensions: ["jsx"],
  },
})
```

It's doesn't help. The issue still not resolved. (

**Comment by martinpengellyphillips** [comment]
For reference, I tested by creating a new repo from the solid ts template, updated all dependencies to latest and installed solid-dnd. This worked for me 🤷‍♂️

I'll need more info to help further:
- What versions of solid, vite, vite-solid-plugin do you have? 
- What does your package.json look like?
- Do you have a repo I can look at?

**Comment by membranobruno** [comment]
Perhaps, I found what’s wrong. If I import createDraggable and define  Draggable component directly in App.jsx everything works. But if make component in separate file I see the error on step const draggable = createDraggable()   Maybe I don't understand something fundamental in Solid

**Comment by martinpengellyphillips** [comment]
Are you using the needed `.jsx` (or `.tsx` for typescript) extension for that other file?

**Comment by membranobruno** [comment]
After a few hours of dancing it finally works ))) I made the new project and move all my components there step by step. So, I don't know what exactly was wrong but I'm sure optimizeDeps make sense, because without that option the error appears every time.

**Comment by martinpengellyphillips** [comment]
Good to hear!

Curious: do you still have that alias entry in your vite config? If not, perhaps that was causing an issue.

**Comment by membranobruno** [comment]
My vite config looks exactly like this

```
import { defineConfig } from "vite"
import solidPlugin from "vite-plugin-solid"
const path = require("path")

export default defineConfig({
  plugins: [solidPlugin()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  server: {
    port: 3000,
  },
  build: {
    target: "esnext",
  },
  optimizeDeps: {
    extensions: ["jsx"],
  },
})

```

**Comment by mykhaliuk** [comment]
@martinpengellyphillips sorry for being out of touch. 

You r right: 
```jsx
optimizeDeps: {
    extensions: ["jsx"],
  },
``` 

fixes this issue for me.  Thank you : 🙏

**Comment by kapilpipaliya** [comment]
what this code does?
```
optimizeDeps: {
    extensions: ["jsx"],
  },
```

**Comment by kapilpipaliya** [comment]
we need to delete `node_modules` folder and install packages again also to make it working.

**Comment by riccardoperra** [comment]
I'm not able to use it too and no solution worked for me, except for this:

I basically switch the exports map putting "solid" as last entry 😄

![image](https://user-images.githubusercontent.com/37072694/196525612-1420f6ad-5d2b-4863-84ad-9f09ea880560.png)

There is also reproducible example in a PR for my project where I'm trying to update all dependencies (both solid and solid-dnd)
https://codesandbox.io/p/github/riccardoperra/codeimage/build/update-dependencies?workspace=%7B%22gitSidebarPanel%22:%22PR%22,%22sidebarPanel%22:%22GIT%22%7D

![image](https://user-images.githubusercontent.com/37072694/196526281-4a1838d5-f9d0-4748-aa6f-960e4f8d49ea.png)

**Comment by bioshazard** [comment]
I just ran into this error. Looks like the `var useDragDropContext` in `dev.jsx` is returning a `null` when attempting to `useContext` from `Context` generated higher up from Solid's direct `createContext`. I suspect it's due to my use in a condition render... will update here if I solve it.

**Comment by bioshazard** [comment]
@martinpengellyphillips , I ran into this issue an was able to drill down to see that useDragDropContext from dev.jsx was returning `null`. I was able to replicate it by commenting out the `DragDropProvider` and `DragDropSensors` from one of the Solid examples:

```
const DragDemo = () => {
  return (
    // <DragDropProvider>
    //   <DragDropSensors>
        <Sandbox />
    //   </DragDropSensors>
    // </DragDropProvider>
  );
};
```

I suspect the trouble in my actual codebase is due to putting the provider inside a conditional render or something. Going to try to start small and add to a working example until I break it, but hopefully this insight helps show what might be happening. Definitely a failure of the context not being available during the `createXable` function.

**Comment by bioshazard** [comment]
So in my case, I was making a wrapper for DND components and was using `{children}`. SolidJS expects you to return children as a function to comply with how it does reactivity ( https://www.solidjs.com/tutorial/props_children ). So after complying with the reactivity correctly, it all works just fine. Not sure if this was the case for others, but in my case it came down to bad reactivity.
