### ISSUE TITLE
Example for dnd with a router link

### ISSUE THREAD

**Issue by membranobruno** [thisbeyond/solid-dnd#64]
Hi, this not an issue, but I don't know where to ask. How can I resolve the situation if the element is the <A> link but have to be draggable as well?

for example 
`<A href="/">
			<div class="widget" use:draggable>
				<div class="widget-title">
					Some title
				</div>
				<div class="widget-description" >
					<p>Some description</p>
				</div>
			</div>
		</A>`

Mousedown and drag conflicts with a click. Thanks for any help

**Comment by membranobruno** [comment]
And another one question. Is it possible to add use:draggable dynamically?  If (true) the is element is draggable, if (false) is not draggable. Thanks again

**Comment by martinpengellyphillips** [comment]
Here's an example for both: https://codesandbox.io/s/gallant-germain-jz190k?file=/src/main.tsx

To prevent clicks during drag, we add a global listener to cancel clicks whilst the drag is active. For conditional drag we toggle adding the event listeners on the element.

Hope that helps. I'll likely add these to the website as well as good examples.
