### ISSUE TITLE
I have a JSX issue

### ISSUE THREAD

**Issue by chlbri** [thisbeyond/solid-dnd#66]
When I try to create a component, I have this error:

[vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.

I use the Conditional Drop example from the [website](https://solid-dnd.com/)

**Comment by martinpengellyphillips** [comment]
See https://github.com/thisbeyond/solid-dnd/issues/53#issuecomment-1272076800 (and if using Astro https://github.com/withastro/astro/issues/5058)

**Comment by chlbri** [comment]
The error is the same for both vite and astro addon.

**Comment by Ehesp** [comment]
Looks like a fix for astro is coming in; https://github.com/withastro/astro/pull/5437

**Comment by Ehesp** [comment]
Release for Astro is live.
