### ISSUE TITLE
Drag overlay layout not used for collision detection

### ISSUE THREAD

**Issue by martinpengellyphillips** [thisbeyond/solid-dnd#7]
Currently it is assumed that the drag overlay will have the same dimensions as the draggable it represents. But that is not always true. As a result, a droppable may not activate even if a drag overlay appears over it (because the underlying draggable layout is actually smaller).

Instead should use drag overlay layout in collision detection (when a drag overlay is being used).

**Comment by MarvinRudolph** [comment]
Hey! Any update on this? Can I somehow prevent this with a custom collisionDetector?

**Comment by martinpengellyphillips** [comment]
Thanks!

Interesting. The dnd state will be the authority for collision detection (using the layout and transform of the overlay). So I would expect your solution to not work as expected, as your changes are applied outside of the state.

I might be introducing an `offset` modifier though which could be useful for this case. Longer term I'll consider more robust and flexible "modifiers" support. I'll keep your use case in mind. 

Note the refactor _will_ center the `DragOverlay` over the source draggable on drag start, which might be what you wanted anyway.

**Comment by MarvinRudolph** [comment]
This sounds really cool, thanks! Now I'm even more excited, can't wait to test it out. 😄

**Comment by martinpengellyphillips** [comment]
This is now fixed in [0.7.0](https://github.com/thisbeyond/solid-dnd/releases/tag/0.7.0) with `DragOverlay` being used for collision detection.

In addition:
* `DragOverlay` is auto-centered on the `Draggable` on drag start.
* You can specify custom transformers for items (see example in release notes).
