### ISSUE TITLE
How to use custom elements in a `SortableProvider` and not the `<Sortable/>` component.

### ISSUE THREAD

**Issue by cohenerickson** [thisbeyond/solid-dnd#72]
# Issue

The `<Sortable/>` component seems to be the only way to create draggable elements in my testing. I have tried changing it for regular divs but that didn't work. I also tried adding the `sortable` class but that didn't change my outcome. There appears to be a lack of documentation on everything here so there is likely something that I am missing on how to do this.

# Expected Behavior

When supplying custom elements into the `<SortableProvider>` for them to become sortable.

```TSX
<SortableProvider ids={ids()}>
  <For each={items()}>{(item) => <div class="sortable">{item}</div>}</For>
</SortableProvider>
```

**Comment by cohenerickson** [comment]
Well... I didn't even look at where sortable was defined lol.

**Comment by martinpengellyphillips** [comment]
Yeah, you can have complete control via the `createSortable` directive. 

At some point I'll get around to adding better explanatory docs :)
