### ISSUE TITLE
Sortable Objects

### ISSUE THREAD

**Issue by laurent512** [thisbeyond/solid-dnd#81]
Hello, 

First of all , thank you so much for the very useful library, it is a big timesaver for me and it helps quite a lot the solid ecosystem.

I am currently struggling to make sortable objects (with multiple containers) 
 
Could you please let me know how to tune the multiple container example available to accept them ? 
For example multiple lists containing such objects :  { order : 1 , tasks : { name : "doing groceries" , description : " purchase this that and that" }}

Thank you so much ! :)

**Comment by martinpengellyphillips** [comment]
👋 I've updated the board example on solid-dnd.com to be more real-world. It now uses objects and a calculated 'order' value. Hope that helps.

**Comment by laurent512** [comment]
that's so cool, thank you so much !
