### ISSUE TITLE
Get current droppable on onDragMove

### ISSUE THREAD

**Issue by Itisfilipe** [thisbeyond/solid-dnd#94]
I need to access the current droppable from `onMouseOver` so I can apply dynamic transformations based on the current droppable I am moving over, is that easily achievable?  I was looking at the code and wondering if it isn't possible to add it to the `onDragMove` handler in the same way, it is done for `onDragOver`.

https://github.com/thisbeyond/solid-dnd/blob/main/src/drag-drop-context.tsx#L715-L736

**Comment by martinpengellyphillips** [comment]
Could you explain more your use case - particularly why using `onDragOver` doesn’t suffice?
