### ISSUE TITLE
Trying to render a custom component as sortable

### ISSUE THREAD

**Issue by ZanzyTHEbar** [thisbeyond/solid-dnd#99]
I want to like this library, so far it seems well-built and i love the solid forward approach. 

I am trying to render a vertically sortable list of custom components, and i am having trouble. Perhaps someone could help me see my issue. 

Here is a gist of my current [code](https://gist.github.com/ZanzyTHEbar/a6b104bf6e16453e6c94a25ee54dd9e4)

I am trying to render the `TriggerComponent` `N` number of times (based onthe number of objects in the store), and pass it the values from my store, and make each rendered instance draggable. However, my current attempt is only dragging the id member of the store object and i cant seem to get the component itself to drag properly. 

Its late, I've been staring at this for awhile, and its probably something obvious. Any help would be appreciated.

**Comment by martinpengellyphillips** [comment]
As you are using the overlay component, you need to manage rendering what you want to see as the active drag component. This can be any component, but must not create a new draggable (e.g. Presentation only). In your case it means you want to render the trigger component as a child of the overlay.

**Comment by ZanzyTHEbar** [comment]
> 

That makes sense, thank you - ill give it a go.

**Comment by martinpengellyphillips** [comment]
Did it work? If so, please close this issue.

**Comment by ZanzyTHEbar** [comment]
i moved on to a different library, this one did was far too obtuse to use. Will come back when this has proper docs and more active development. Would be a great library though, if so.
